services:
  db: 
    image: postgres:alpine
    container_name: sickfits-db-cnt
    restart: always
    ports:
      - "5435:5432"
    env_file:
     - ./.envs/db.env
    volumes:
      - pg-data:/var/lib/postgresql/data

  db-admin:
    image: adminer
    container_name: sickfits-admin-cnt
    restart: always
    ports:
      - "8000:8080"
    environment:
      - ADMINER_DESIGN=dracula

volumes:
  pg-data:
  